version: '3'
services:
  backend:
    build: ./backend
    command: python3 app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code

  frontend:
    build: ./frontend
    command: yarn serve
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"